### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by JellyTony** [iDerekLi/juejin-helper#63]
/home/runner/work/juejin-helper/juejin-helper/node_modules/node-fetch/lib/index.js:273
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://juejin-game.bytedance.com/game/sea-gold/game/over?uid=xx&time=xxx reason: Unexpected token < in JSON at position 0
    at /home/runner/work/juejin-helper/juejin-helper/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Seagold.request (/home/runner/work/juejin-helper/juejin-helper/node_modules/juejin-helper/dist/juejin-helper.cjs.js:45:37)
    at async SeaGold.gameOver (/home/runner/work/juejin-helper/juejin-helper/scripts/seaGold.js:104:[26](https://github.com/JellyTony/juejin-helper/runs/7684692434?check_suite_focus=true#step:4:27))
    at async runGame (/home/runner/work/juejin-helper/juejin-helper/scripts/seaGold.js:[33](https://github.com/JellyTony/juejin-helper/runs/7684692434?check_suite_focus=true#step:4:34)8:16)
    at async SeaGold.run (/home/runner/work/juejin-helper/juejin-helper/scripts/seaGold.js:361:7)
    at async run (/home/runner/work/juejin-helper/juejin-helper/scripts/seaGold.js:414:5) {
  type: 'invalid-json'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by iDerekLi** [comment]
更新至最新平台Cookie就可以了

**Comment by iDerekLi** [comment]
工程已重构，建议 Fetch 到最新。🥰玩的愉快～ #64
