### ISSUE TITLE
action报错但是正常签到

### ISSUE THREAD

**Issue by chaseleaf** [iDerekLi/juejin-helper#89]
签到正常，但每次github都提示报错，具体报错信息如下：
`Error : moveUp代码块不足
    at /home/runner/work/juejin-helper/juejin-helper/workflows/node_modules/juejin-helper/build/juejin-helper.c.js:524:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Seagold.executeGameCommand (/home/runner/work/juejin-helper/juejin-helper/workflows/seagold.js:135:29)
    at async runGame (/home/runner/work/juejin-helper/juejin-helper/workflows/seagold.js:343:14)
    at async Seagold.run (/home/runner/work/juejin-helper/juejin-helper/workflows/seagold.js:3[76](https://github.com/chaseleaf/juejin-helper/actions/runs/3527644705/jobs/5916938232#step:4:77):28)
    at async run (/home/runner/work/juejin-helper/juejin-helper/workflows/seagold.js:414:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command .
Error :  Process completed with exit code 1.`
![image](https://user-images.githubusercontent.com/53562961/203445938-06a864c5-242b-468d-ba21-b3c96bb6dc0a.png)

**Comment by qinfeng0214** [comment]
自己玩几把，换个地图
